### ISSUE TITLE
Error when using the included components

### ISSUE THREAD

**Issue by GauravShetty1016** [ember-mobile/ember-cli-framework7#19]
The components code tries to call framweork7 js methods on the f7 service variable instead of the f7 attribute in the f7 service that contains the actual initialized framwork7 object.
I have raised a PR to fix this issue. https://github.com/ember-mobile/ember-cli-framework7/pull/18

**Comment by spieker** [comment]
Thank you, I appreciate your work. I promise to start a rework of all of this soon.

**Comment by engwan** [comment]
Yeah, I encountered this problem too. It's not clearly documented that we need to use the f7 attribute of the f7 service.

Even the samples say:

`this.get('f7').alert('Some alert');`

Instead of just changing the components to use `this.get('f7.f7')`, maybe we should also proxy function calls on the f7 service to the f7 attribute. So we don't have to do the weird looking 'f7.f7'

**Comment by spieker** [comment]
@engwan I already started a rewrite of the addon but I don't have that much time so it's not published as a new version yet. But you can try to use the **develop** branch of the addon, there I already proxy the methods on the service.
